#### Membership
#address=127.0.0.1
protocol.membership.samplesize=6
protocol.membership.sampletime=2000
protocol_metrics_interval=-1
channel_metrics_interval=-1

# Cyclon
protocol.membership.cyclon.maxN=8
protocol.membership.cyclon.shuffle_time=2000
protocol.membership.cyclon.subset_size=4

# HyParView
protocol.membership.hyparview.active_size=5
protocol.membership.hyparview.passive_size=20
protocol.membership.hyparview.arwl=5
protocol.membership.hyparview.prwl=2

protocol.membership.hyparview.shuffle_ttl=3
protocol.membership.hyparview.shuffle_period=4000
protocol.membership.hyparview.shuffle_k_active=3
protocol.membership.hyparview.shuffle_k_passive=4

#### Dissemination

#### App
app.payload.size 20
app.broadcast.period 3000
app.op.folder /home/distalg06/operations
app.op.start.file go.flag
app.of.fail.file fail.flag
app.op.file.pool 1000

#### Broadcast

# EagerPush
protocol.broadcast.eagerpush.fanout=3

# Hybrid
protocol.broadcast.hybrid.eager_fanout=3
protocol.broadcast.hybrid.lazy_fanout=2
protocol.broadcast.hybrid.min_eager_fanout=2
protocol.broadcast.hybrid.max_eager_fanout=5
protocol.broadcast.hybrid.adapt_window=12