#### Membership
protocol.membership.sampletime 2000
protocol.membership.samplesize 6
#### Channel metrics on Membership
protocol_metrics_interval -1
channel_metrics_interval -1

#### Dissemination

#### App
app.payload.size 20
app.broadcast.period 3000
app.op.folder /Users/jleitao/operations
app.op.start.file go.flag
app.of.fail.file fail.flag
app.op.file.pool 1000